language: php
sudo: false
dist: xenial

cache:
    directories:
        - $HOME/.composer/cache

env:
    - 'ES_ENDPOINT=http://localhost:9200'

matrix:
    fast_finish: true
    include:
        - stage: Test
          php: 7.3
          env: PHPUNIT_FLAGS='--coverage-clover=coverage.clover'
        - stage: Test
          php: 7.3
          env: SYMFONY_VERSION=4.4.*
        - stage: Test
          php: 7.3
          env: SYMFONY_VERSION=4.3.*

before_install:
    - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.3.0.deb && sudo service elasticsearch restart
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/messenger=$SYMFONY_VERSION; fi
    - composer require fazland/elastica-odm dev-master --no-update

before_script:
    - composer install --no-progress --no-suggest

script:
    - vendor/bin/phpunit $PHPUNIT_FLAGS

after_success:
    - if [ -f coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
