language: php

cache:
    directories:
        - $HOME/.composer/cache

env:
    - 'ES_ENDPOINT=http://localhost:9200'

matrix:
    fast_finish: true
    include:
        - php: 7.3

before_install:
    - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.3.0.deb && sudo service elasticsearch restart

before_script:
    - composer self-update
    - composer require fazland/elastica-odm dev-master --no-update
    - composer install --no-progress --no-suggest

script:
    - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_success:
    - if [ -f coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
